#!/usr/bin/env python3
"""
Script to generate PowerPoint presentation from markdown content.
Requires: pip install python-pptx
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

# Color scheme
PRIMARY_COLOR = RGBColor(249, 115, 22)  # Orange #f97316
SECONDARY_COLOR = RGBColor(120, 113, 108)  # Brown #78716c
ACCENT_COLOR = RGBColor(245, 158, 11)  # Golden #f59e0b
TEXT_COLOR = RGBColor(28, 25, 23)  # Dark Gray #1c1917
BG_COLOR = RGBColor(250, 250, 249)  # Light Gray #fafaf9

def create_presentation():
    """Create PowerPoint presentation"""
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    
    # Define slide layouts
    title_slide_layout = prs.slide_layouts[0]  # Title slide
    content_slide_layout = prs.slide_layouts[1]  # Title and content
    blank_slide_layout = prs.slide_layouts[6]  # Blank slide
    
    # SLIDE 1: Title Slide
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Village Mart"
    subtitle.text = "E-Commerce Platform\nFrontend & Backend Development\n\nProject Overview & Technical Architecture"
    
    # SLIDE 2: Project Introduction
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Project Introduction"
    tf = content.text_frame
    tf.text = "Village Mart - E-Commerce Platform"
    p = tf.add_paragraph()
    p.text = "Project Vision:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Modern e-commerce platform for authentic Indian namkeens and sweets"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Seamless shopping experience across web platforms"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Scalable architecture for future growth"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Key Highlights:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "✓ Modern React-based frontend"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ RESTful API backend (planned)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Responsive design for all devices"
    p.level = 2
    
    # SLIDE 3: Project Scope
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Project Scope"
    tf = content.text_frame
    tf.text = "What's Included"
    p = tf.add_paragraph()
    p.text = "Frontend (Web Application)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Complete user interface"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Product catalog and browsing"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Shopping cart and checkout"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Backend (API Development)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• RESTful API endpoints"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Database design and management"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Authentication & authorization"
    p.level = 2
    
    # SLIDE 4: Frontend Architecture
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Frontend Architecture"
    tf = content.text_frame
    tf.text = "Technology Stack"
    p = tf.add_paragraph()
    p.text = "Core Framework:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• React 19.1.1 (Latest version)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• TypeScript (Type-safe development)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• React Router DOM 7.9.3 (Routing)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "State Management:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Redux Toolkit 2.0.1"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• React Redux 9.0.4"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "UI & Styling:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Tailwind CSS 3.4.18"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Framer Motion 11.0.0 (Animations)"
    p.level = 2
    
    # SLIDE 5: Frontend Features - Core
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Frontend Features - Core"
    tf = content.text_frame
    tf.text = "Core E-Commerce Features"
    p = tf.add_paragraph()
    p.text = "Product Management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Product catalog with grid/list view"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Product details with images"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Real-time search functionality"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Advanced filtering (category, price, rating)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Shopping Cart"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Add/remove products"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Quantity management"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Real-time price calculation"
    p.level = 2
    
    # SLIDE 6: Frontend Features - UX
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Frontend Features - UX"
    tf = content.text_frame
    tf.text = "User Experience Features"
    p = tf.add_paragraph()
    p.text = "User Authentication"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Login/Logout system"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Protected routes"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Session management"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Checkout Process"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Multi-step checkout"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Form validation"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Address management"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "UI/UX Features"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Dark/Light theme toggle"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Multi-language support"
    p.level = 2
    
    # SLIDE 7: Frontend Project Structure
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Frontend Project Structure"
    tf = content.text_frame
    tf.text = "Organized Codebase"
    p = tf.add_paragraph()
    p.text = "frontend/src/"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• api/ - API service layer"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• components/ - Reusable components"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• screens/ - Page components"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• store/ - Redux store"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• theme/ - Theme configuration"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Statistics:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• 20+ reusable components"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• 9 main screens"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• 100% TypeScript"
    p.level = 2
    
    # SLIDE 8: Frontend Design System
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Frontend Design System"
    tf = content.text_frame
    tf.text = "Consistent Design Language"
    p = tf.add_paragraph()
    p.text = "Color Palette:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Primary: Orange (#f97316)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Secondary: Brown (#78716c)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Accent: Golden (#f59e0b)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Typography:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Font: Inter, system-ui, sans-serif"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Responsive font sizes (12px - 48px)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Animations:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Fade in, Slide up, Bounce effects"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Smooth transitions (0.6s - 0.8s)"
    p.level = 2
    
    # SLIDE 9: Frontend Performance
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Frontend Performance"
    tf = content.text_frame
    tf.text = "Optimization Strategies"
    p = tf.add_paragraph()
    p.text = "Code Optimization:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "✓ Code splitting & lazy loading"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Tree shaking"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Bundle optimization"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Performance Metrics:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• First Contentful Paint: < 1.5s"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Largest Contentful Paint: < 2.5s"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Time to Interactive: < 3s"
    p.level = 2
    
    # SLIDE 10: Backend Scope - Overview
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Scope - Overview"
    tf = content.text_frame
    tf.text = "Backend API Requirements"
    p = tf.add_paragraph()
    p.text = "Purpose:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Provide RESTful API endpoints for frontend"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Manage database operations"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Handle business logic"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Secure authentication & authorization"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Technology Options:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Node.js + Express.js (Recommended)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Python + Django/FastAPI"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Database:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• PostgreSQL (Recommended)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• MySQL or MongoDB"
    p.level = 2
    
    # SLIDE 11: Backend API - Products
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend API - Products"
    tf = content.text_frame
    tf.text = "Product Management APIs"
    p = tf.add_paragraph()
    p.text = "GET /api/products"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Fetch all products"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Query parameters: category, price, rating, search"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Pagination support"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "GET /api/products/:id"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Fetch single product details"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "POST /api/products (Admin)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Create new product"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Image upload support"
    p.level = 2
    
    # SLIDE 12: Backend API - Users
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend API - Users"
    tf = content.text_frame
    tf.text = "User Management APIs"
    p = tf.add_paragraph()
    p.text = "POST /api/auth/register"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• User registration"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Email verification"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "POST /api/auth/login"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• User authentication"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• JWT token generation"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "GET /api/users/profile (Protected)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Get user profile"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "PUT /api/users/profile (Protected)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Update user profile"
    p.level = 2
    
    # SLIDE 13: Backend API - Orders
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend API - Orders"
    tf = content.text_frame
    tf.text = "Order Management APIs"
    p = tf.add_paragraph()
    p.text = "GET /api/orders"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Fetch user orders (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Admin: Fetch all orders"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "POST /api/orders"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Create new order (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Validate cart items"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Calculate totals"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "PUT /api/orders/:id/status (Admin)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Update order status"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "GET /api/orders/tracking/:id"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Track order status"
    p.level = 2
    
    # SLIDE 14: Backend API - Cart & Wishlist
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend API - Cart & Wishlist"
    tf = content.text_frame
    tf.text = "Shopping Cart & Wishlist APIs"
    p = tf.add_paragraph()
    p.text = "Cart APIs:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• GET /api/cart - Get user cart (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• POST /api/cart/add - Add item (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• PUT /api/cart/update/:id - Update quantity (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• DELETE /api/cart/remove/:id - Remove item (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Wishlist APIs:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• GET /api/wishlist - Get wishlist (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• POST /api/wishlist/add - Add to wishlist (Protected)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• DELETE /api/wishlist/remove/:id - Remove item (Protected)"
    p.level = 2
    
    # SLIDE 15: Backend Database Design
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Database Design"
    tf = content.text_frame
    tf.text = "Database Schema Overview"
    p = tf.add_paragraph()
    p.text = "Core Tables:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Users - id, email, password_hash, name, phone, addresses"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Products - id, name, description, price, category, images, stock"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Orders - id, user_id, total, status, shipping_address"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Order Items - id, order_id, product_id, quantity, price"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Cart - id, user_id, product_id, quantity"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Wishlist - id, user_id, product_id"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Categories - id, name, description, image"
    p.level = 2
    
    # SLIDE 16: Backend Architecture
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Architecture"
    tf = content.text_frame
    tf.text = "Proposed System Architecture"
    p = tf.add_paragraph()
    p.text = "Components:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• API Gateway (Express.js)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Authentication Middleware (JWT)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Business Logic Layer"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Data Access Layer"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Database (PostgreSQL)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Cache Layer (Redis - optional)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Architecture Flow:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "Frontend → Backend API → Database"
    p.level = 2
    
    # SLIDE 17: Backend Security
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Security"
    tf = content.text_frame
    tf.text = "Security Implementation"
    p = tf.add_paragraph()
    p.text = "Authentication & Authorization:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• JWT (JSON Web Tokens)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Password hashing (bcrypt)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Role-based access control"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "API Security:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• HTTPS/SSL encryption"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• CORS configuration"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Rate limiting"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Input validation & sanitization"
    p.level = 2
    
    # SLIDE 18: Backend Features - Core
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Features - Core"
    tf = content.text_frame
    tf.text = "Core Backend Features"
    p = tf.add_paragraph()
    p.text = "Authentication System:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• User registration & login"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• JWT token-based authentication"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Password reset functionality"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Product Management:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• CRUD operations for products"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Image upload & storage"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Category management"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Cart Management:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Persistent cart storage"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Real-time price calculation"
    p.level = 2
    
    # SLIDE 19: Backend Features - Advanced
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Features - Advanced"
    tf = content.text_frame
    tf.text = "Advanced Backend Features"
    p = tf.add_paragraph()
    p.text = "Order Processing:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Order creation & validation"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Order status tracking"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Email notifications"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Payment Integration:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Payment gateway integration (Razorpay/Stripe)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Payment verification"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Refund processing"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Admin Features:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Admin dashboard API"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• User management"
    p.level = 2
    
    # SLIDE 20: Backend Technology Stack
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Technology Stack"
    tf = content.text_frame
    tf.text = "Recommended Technologies"
    p = tf.add_paragraph()
    p.text = "Backend Framework:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Node.js 18+ (Runtime)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Express.js 4.x (Web framework)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• TypeScript (Type safety)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Database:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• PostgreSQL 14+ (Primary database)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Redis (Caching - optional)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Authentication:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• jsonwebtoken (JWT)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• bcrypt (Password hashing)"
    p.level = 2
    
    # SLIDE 21: System Integration
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "System Integration"
    tf = content.text_frame
    tf.text = "Frontend-Backend Integration"
    p = tf.add_paragraph()
    p.text = "API Communication:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• RESTful API endpoints"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• JSON data format"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Axios for HTTP requests"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Data Flow:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "User Action → API Service → HTTP Request → Backend API → Database → Response → Redux Store → UI Update"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Environment Configuration:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Development: http://localhost:5000/api"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Production: https://api.villagemart.com"
    p.level = 2
    
    # SLIDE 22: Development Workflow
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Development Workflow"
    tf = content.text_frame
    tf.text = "Development Process"
    p = tf.add_paragraph()
    p.text = "Frontend Development:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "1. Component development"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "2. State management setup"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "3. API integration"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "4. UI/UX implementation"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Backend Development:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "1. Database schema design"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "2. API endpoint development"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "3. Authentication implementation"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "4. Business logic implementation"
    p.level = 2
    
    # SLIDE 23: Testing Strategy
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Testing Strategy"
    tf = content.text_frame
    tf.text = "Quality Assurance"
    p = tf.add_paragraph()
    p.text = "Frontend Testing:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Unit tests (Jest, React Testing Library)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Component testing"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Integration testing"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• E2E testing (Cypress - planned)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Backend Testing:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Unit tests (Jest/Mocha)"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• API endpoint testing"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Database testing"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Test Coverage Target:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Frontend: 70%+"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Backend: 80%+"
    p.level = 2
    
    # SLIDE 24: Deployment Strategy
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Deployment Strategy"
    tf = content.text_frame
    tf.text = "Production Deployment"
    p = tf.add_paragraph()
    p.text = "Frontend Deployment:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Platform: Netlify / Vercel / AWS S3"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Build: npm run build"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• CDN: CloudFront / Cloudflare"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Backend Deployment:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Platform: AWS EC2 / Heroku / Railway"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Database: AWS RDS / Managed PostgreSQL"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• SSL: Let's Encrypt / AWS Certificate Manager"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "CI/CD Pipeline:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• GitHub Actions / GitLab CI"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Automated testing & deployment"
    p.level = 2
    
    # SLIDE 25: Project Statistics
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Project Statistics"
    tf = content.text_frame
    tf.text = "Development Metrics"
    p = tf.add_paragraph()
    p.text = "Frontend:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Components: 20+ reusable components"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Pages: 9 main screens"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Lines of Code: ~15,000+"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• TypeScript Coverage: 100%"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Backend (Planned):"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• API Endpoints: 30+ endpoints"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Database Tables: 7+ tables"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Services: 10+ service modules"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Project Timeline:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Frontend: ✓ Completed"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Backend: 🚧 In Development"
    p.level = 2
    
    # SLIDE 26: Key Achievements
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Key Achievements"
    tf = content.text_frame
    tf.text = "Frontend Accomplishments"
    p = tf.add_paragraph()
    p.text = "Modern Technology Stack"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "✓ Latest React 19 with TypeScript"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Redux Toolkit for state management"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Tailwind CSS for styling"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Complete Feature Set"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "✓ Product catalog & search"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Shopping cart & checkout"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ User authentication"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Excellent User Experience"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "✓ Responsive design"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Dark/Light themes"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "✓ Multi-language support"
    p.level = 2
    
    # SLIDE 27: Backend Development Plan
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Backend Development Plan"
    tf = content.text_frame
    tf.text = "Implementation Roadmap"
    p = tf.add_paragraph()
    p.text = "Phase 1: Foundation (Week 1-2)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Database schema design"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Project setup & structure"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Authentication system"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Phase 2: Core Features (Week 3-4)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Product management APIs"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Cart & wishlist APIs"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Order management APIs"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Phase 3: Advanced Features (Week 5-6)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Payment integration"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Email notifications"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Admin APIs"
    p.level = 2
    
    # SLIDE 28: Future Enhancements
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Future Enhancements"
    tf = content.text_frame
    tf.text = "Planned Features"
    p = tf.add_paragraph()
    p.text = "Short-term (3 months):"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Payment gateway integration"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Email notifications"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Order tracking"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Product reviews & ratings"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Medium-term (6 months):"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Real-time notifications"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Advanced analytics"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Recommendation engine"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Long-term (12 months):"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• Mobile app API support"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• AI-powered search"
    p.level = 2
    
    # SLIDE 29: Challenges & Solutions
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Challenges & Solutions"
    tf = content.text_frame
    tf.text = "Technical Challenges"
    p = tf.add_paragraph()
    p.text = "Challenge 1: State Management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "Solution: Redux Toolkit for centralized state"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Challenge 2: API Integration"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "Solution: Axios with interceptors for consistent API calls"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Challenge 3: Performance"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "Solution: Code splitting, lazy loading, caching"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Challenge 4: Responsive Design"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "Solution: Mobile-first approach with Tailwind CSS"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Challenge 5: Security"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "Solution: JWT authentication, input validation, HTTPS"
    p.level = 2
    
    # SLIDE 30: Conclusion
    slide = prs.slides.add_slide(content_slide_layout)
    title = slide.shapes.title
    content = slide.placeholders[1]
    title.text = "Conclusion"
    tf = content.text_frame
    tf.text = "Project Summary"
    p = tf.add_paragraph()
    p.text = "Village Mart is a comprehensive e-commerce platform with:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "Modern Frontend"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• React 19 + TypeScript"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Complete shopping experience"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Production-ready codebase"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Backend Development"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "• RESTful API architecture"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Secure authentication"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "• Scalable database design"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "Next Steps:"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "1. Complete backend development"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "2. Frontend-backend integration"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "3. Comprehensive testing"
    p.level = 2
    p = tf.add_paragraph()
    p.text = "4. Production deployment"
    p.level = 2
    
    # SLIDE 31: Thank You
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Thank You"
    subtitle.text = "Questions & Discussion\n\nContact Information:\nProject Repository: [GitHub URL]\nDocumentation: Available in project folder"
    
    # Save presentation
    prs.save('Village_Mart_Presentation.pptx')
    print("PowerPoint presentation created successfully: Village_Mart_Presentation.pptx")

if __name__ == "__main__":
    try:
        create_presentation()
    except ImportError:
        print("Error: python-pptx library not found.")
        print("Please install it using: pip install python-pptx")
    except Exception as e:
        print(f"Error creating presentation: {e}")


